server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Public routes (login & register)
        - id: user-service-auth
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        # Protected routes (require JWT)
        - id: user-service-secure
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
            - JwtAuthFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

jwt:
  # The updated 256-bit (32-byte) Base64 encoded secret key.
  # This must match the key used in the 'user-service' to validate tokens.
  secret: dGhlMjU2Yml0U2VjcmV0S2V5Rm9ySGFzaDI1NlRva2Vucw==